In [2]:
import numpy as np

In [3]:
my_secret = [x for x in range(1, 301, 7) if x%10 == 7 or x%10 == 1]
np.array([my_secret, [x/2 for x in my_secret], [x-100 for x in my_secret]])

array([[  1. ,  57. ,  71. , 127. , 141. , 197. , 211. , 267. , 281. ],
       [  0.5,  28.5,  35.5,  63.5,  70.5,  98.5, 105.5, 133.5, 140.5],
       [-99. , -43. , -29. ,  27. ,  41. ,  97. , 111. , 167. , 181. ]])

In [21]:
display(np.ones(5))
#display(np.ones(5,5))
display(np.ones((5,5)))
display(np.eye(5))
display(np.full((5,5), 1))
display(np.array([[1,2,3,4,5], [5,1,2,3,4], [4,5,1,2,3], [3,4,5,1,2], [2,3,4,5,1]])) 

array([1., 1., 1., 1., 1.])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

array([[1, 2, 3, 4, 5],
       [5, 1, 2, 3, 4],
       [4, 5, 1, 2, 3],
       [3, 4, 5, 1, 2],
       [2, 3, 4, 5, 1]])

In [23]:
display(np.random.randint(0, 4, (3, 3)) )
display(np.random.randint(0, 5, (3, 3)) )
display(np.random.randint(0, 6, (3, 3)) )
display(np.random.randint(0, 5, 3) )

array([[1, 0, 0],
       [0, 0, 2],
       [2, 0, 1]])

array([[2, 4, 2],
       [0, 2, 1],
       [3, 0, 1]])

array([[4, 5, 2],
       [1, 1, 0],
       [3, 2, 2]])

array([2, 4, 0])

In [24]:
display(np.array(range(9)) )
display(np.ones((2,2,2)) )
display(np.array([i for i in range(11) if i%2]) )
display(np.arange(1, 14, 2) )

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

array([1, 3, 5, 7, 9])

array([ 1,  3,  5,  7,  9, 11, 13])