In [1]:
import numpy as np

In [2]:
my_array = np.array([x for x in range(10)])
display(my_array[5])
display(my_array[-1])
display(my_array[3:6])
display(my_array[1:8:3])

5

9

array([3, 4, 5])

array([1, 4, 7])

In [3]:
my_array = np.array([[1,2,3,4],
                     [10,11,12,13],
                     [45,46,47,48]])
display(my_array[1][2])
display(my_array[1,2])

12

12

# Упражнения

Потренируемся извлекать из двумерного массива отдельные элементы и их срезы и производить над ними математические действия. Задания блока будем выполнять на примере массива, созданного кодом:

In [43]:
first_line = [x*y for x in range(2, 100, 6) for y in range (7, 1, -2)]
second_line = [x ** 0.5 for x in range(1000, 1101, 2)]
third_line = [x**2 for x in range(51)]

big_secret = np.array([first_line, second_line, third_line, second_line, first_line])

###### Пока мы не научились применять функции NumPy к массивам и их фрагментам, используйте цикл с параметром для организации вычислений.

#### Чему равна сумма элементов последнего столбца массива? Ответ округлите до двух цифр после запятой:

In [5]:
big_secret[:,-1].sum()

3154.332495807108

#### Выделите из каждой строки массива big_secret первые 5 элементов. Чему равна сумма элементов главной диагонали получившейся матрицы? Округлите ответ до двух цифр после запятой:

In [6]:
new_array = big_secret[:, 0:6]
j=0
sum=0
for i in new_array:
    sum+=new_array[j,j]
    j+=1
round(sum,2)

121.37

#### Выделите из каждой строки массива big_secret последние 5 элементов. Чему равно произведение элементов главной диагонали получившейся матрицы? Введите полученный результат без изменений и округлений.

In [25]:
new_array = big_secret[:, -5:]
print(new_array)
diag=1
for i in range(5):
    diag=diag*new_array[i,i]
    print(new_array[i,i])
print(diag)

[[ 460.          276.          686.          490.          294.        ]
 [  33.04542328   33.07567082   33.10589071   33.13608305   33.1662479 ]
 [2116.         2209.         2304.         2401.         2500.        ]
 [  33.04542328   33.07567082   33.10589071   33.13608305   33.1662479 ]
 [ 460.          276.          686.          490.          294.        ]]
460.0
33.075670817082454
2304.0
33.13608305156178
294.0
341505315559.2347


# Упражнения
Продолжим работать с массивом big_secret. Замените на 1 все элементы, у которых оба индекса нечётные, и на -1 все элементы, у которых оба индекса чётные.

In [44]:
new_array=big_secret
print(big_secret[0:5,0:5])
print('=============================================================================')
print(new_array[0:5,0:5])
print('================================================================================')
slice_x1=new_array[1::2,1::2]
slice_x1[:]=1
slice_x2=new_array[::2,::2]
slice_x2[:]=-1
print(new_array[0:5,0:5])

[[14.         10.          6.         56.         40.        ]
 [31.6227766  31.65438358 31.68595904 31.71750305 31.74901573]
 [ 0.          1.          4.          9.         16.        ]
 [31.6227766  31.65438358 31.68595904 31.71750305 31.74901573]
 [14.         10.          6.         56.         40.        ]]
[[14.         10.          6.         56.         40.        ]
 [31.6227766  31.65438358 31.68595904 31.71750305 31.74901573]
 [ 0.          1.          4.          9.         16.        ]
 [31.6227766  31.65438358 31.68595904 31.71750305 31.74901573]
 [14.         10.          6.         56.         40.        ]]
[[-1.         10.         -1.         56.         -1.        ]
 [31.6227766   1.         31.68595904  1.         31.74901573]
 [-1.          1.         -1.          9.         -1.        ]
 [31.6227766   1.         31.68595904  1.         31.74901573]
 [-1.         10.         -1.         56.         -1.        ]]


#### Выделите из каждой строки обновлённого массива big_secret первые 5 элементов. Чему равна сумма элементов главной диагонали получившейся матрицы? Введите полученный ответ без изменений и округлений.

In [48]:
print(big_secret[:,:6])
summ=0
sum_array=big_secret[:,:6]
for i in range(5):
    summ=summ+sum_array[i,i]
print('================================================================================')
print(summ)

[[-1.         10.         -1.         56.         -1.         24.        ]
 [31.6227766   1.         31.68595904  1.         31.74901573  1.        ]
 [-1.          1.         -1.          9.         -1.         25.        ]
 [31.6227766   1.         31.68595904  1.         31.74901573  1.        ]
 [-1.         10.         -1.         56.         -1.         24.        ]]
-1.0


#### Выделите из каждой строки обновлённого массива big_secret последние 5 элементов. Чему равно произведение элементов главной диагонали получившейся матрицы? Введите полученный результат без изменений и округлений.

In [50]:
print(big_secret[:,-5:])
diag=big_secret[:,-5:]
print('================================================================================')
print(diag)
j=1
for i in range(5):
    j=j*diag[i,i]
print('================================================================================')
print(j)

[[-1.00000000e+00  2.76000000e+02 -1.00000000e+00  4.90000000e+02
  -1.00000000e+00]
 [ 3.30454233e+01  1.00000000e+00  3.31058907e+01  1.00000000e+00
   3.31662479e+01]
 [-1.00000000e+00  2.20900000e+03 -1.00000000e+00  2.40100000e+03
  -1.00000000e+00]
 [ 3.30454233e+01  1.00000000e+00  3.31058907e+01  1.00000000e+00
   3.31662479e+01]
 [-1.00000000e+00  2.76000000e+02 -1.00000000e+00  4.90000000e+02
  -1.00000000e+00]]
[[-1.00000000e+00  2.76000000e+02 -1.00000000e+00  4.90000000e+02
  -1.00000000e+00]
 [ 3.30454233e+01  1.00000000e+00  3.31058907e+01  1.00000000e+00
   3.31662479e+01]
 [-1.00000000e+00  2.20900000e+03 -1.00000000e+00  2.40100000e+03
  -1.00000000e+00]
 [ 3.30454233e+01  1.00000000e+00  3.31058907e+01  1.00000000e+00
   3.31662479e+01]
 [-1.00000000e+00  2.76000000e+02 -1.00000000e+00  4.90000000e+02
  -1.00000000e+00]]
-1.0
