In [2]:
import numpy as np

In [6]:
a = np.array([3,6,9])
b = np.array([12,15,18])

result1 = a+b
result2 = b-a
result3 = a*b
result4 = a/b
result5 = a*2
print('Сумма: {}\nРазность: {}\nПроизведение: {}\n\
Частное: {}\nУмножение на число: {}'\
      .format(result1, result2, result3, result4, result5))

Сумма: [15 21 27]
Разность: [9 9 9]
Произведение: [ 36  90 162]
Частное: [0.25 0.4  0.5 ]
Умножение на число: [ 6 12 18]


#### Замена местами строк и столбцов двумерного массива называется транспонированием. Для выполнения этой операции в NumPy используется метод T:

In [10]:
my_array = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(np.array([[1,2,3,4,5], [6,7,8,9,10]]))
my_array.T

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

#### Для превращения массива одной размерности в массив другой — обычно для преобразования одномерного массива в многомерный — используется метод reshape. Изменить размерность массива можно только в том случае, если число элементов в исходном и в целевом массиве совпадает:

In [11]:
my_array = np.random.randint(0, 10, 20)
print(np.random.randint(0, 10, 20))
my_array.reshape((4,5))

[7 5 3 2 5 6 7 5 9 4 9 1 9 5 7 4 9 6 0 1]


array([[2, 5, 1, 0, 2],
       [4, 2, 8, 9, 2],
       [3, 3, 5, 5, 8],
       [7, 2, 4, 0, 9]])

#### Для преобразования многомерного массива в одномерный используется метод flatten:

In [12]:
my_array = np.array([[1,2,3], [11,22,33], [111,222,333]])
print(np.array([[1,2,3], [11,22,33], [111,222,333]]))
my_array.flatten()

[[  1   2   3]
 [ 11  22  33]
 [111 222 333]]


array([  1,   2,   3,  11,  22,  33, 111, 222, 333])

#### Научимся сравнивать элементы массива с числом и извлекать из него только те элементы, которые больше или меньше заданного числа. Для этого создадим массив размера 3х4, произвольно заполненный числами от 0 до 10. При создании массива используется генератор случайных чисел, так что у вас могут получиться другие значения:

In [14]:
my_array = np.random.randint(0, 10, (3,4))
print(my_array)
my_array<5

[[7 0 4 8]
 [9 2 7 2]
 [6 5 8 3]]


array([[False,  True,  True, False],
       [False,  True, False,  True],
       [False, False, False,  True]])

#### для того, чтобы получить элементы массива my_array, которые меньше пяти, воспользуемся кодом ниже. Отобранные элементы представляют собой одномерный массив.

In [15]:
my_array[my_array<5]

array([0, 4, 2, 2, 3])

#### Маска нужна для выбора только определенных строк или столбцов из всего массива и скрытия остальных. Маска в Python задаётся при помощи булевых 0 и 1, где 0 скрывает столбец или строку, а 1 оставляет ее на виду. Выведем первый и третрий столбец массива:

In [16]:
mask = np.array([1, 0, 1, 0], dtype=bool)
my_array[:, mask]

array([[7, 4],
       [9, 7],
       [6, 8]])

# Сортировка двумерных массивов
Сортировка выполняется с помощью функции sort, в качестве параметров функция получает сам массив, а также номер оси (0 (для столбцов) или 1 (для строк)) , элементы которой необходимо отсортировать. 

In [3]:
my_array = np.random.randint(0, 10, (4, 6))
np.sort(my_array, axis=1)
np.sort(my_array, axis=0)

array([[2, 4, 2, 8, 5, 0],
       [2, 6, 2, 8, 5, 4],
       [3, 6, 2, 9, 7, 4],
       [7, 9, 6, 9, 8, 5]])